sylius_grid:
    grids:
        app_admin_supplier:
            driver:
                options:
                    class: "%app.model.supplier.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
                state:
                    type: string
                    label: sylius.ui.state
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    trust:
                        type: apply_transition
                        label: app.ui.trust
                        icon: star
                        options:
                            link:
                                route: app_admin_supplier_trust
                                parameters:
                                    id: resource.id
                            class: yellow
                            transition: trust
                            graph: app_supplier
                    delete:
                        type: delete
                    
        app_admin_supplier_show:
            driver:
                options:
                    class: "%app.model.supplier.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                email:
                    type: string
                    label: sylius.ui.email
