winzou_state_machine:
    app_supplier:
        class: "%app.model.supplier.class%"
        property_path: state
        graph: app_supplier
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            trusted: ~
        transitions:
            trust:
                from: [new]
                to: trusted
    sylius_shipment:
        callbacks:
            after:
                assign_shipment_code:
                    on: ['ship']
                    do: ['@App\Core\Shipping\Assigner\ShipmentCodeAssignerInterface', 'assign']
                    args: ['object']
